{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Replication Overall Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"min(mysql_slave_status_slave_io_running) + min(mysql_slave_status_slave_sql_running)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_global_status_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Error Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_slave_status_last_errno", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mysql_slave_status_seconds_behind_master",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO/SQL Thread Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "__auto"
    },
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}